mozilla/network-api

Dockerfile, README.md, app/tox.ini, docker-compose.yml, env.default, requirements.txt
Adds a simple docker interface and adds flake8 linting so that I could add the `app` folder to the commit.
=> Fix #13 - Add docker and linting

.gitignore, README.md, app/networkapi/settings.py, docker-compose.yml, env.default, requirements.txt
Adds CORS, Environ, Static File Server, Test deps, and DRF.
Also configures basic settings.
Relies on #15 landing first.
=> Add all the dependencies and prelim config

app/networkapi/features/admin.py, app/networkapi/settings.py, app/networkapi/templates/features/adminsortable_objects_custom.html, app/networkapi/utility/templatetags/adminsortable_tags_custom.py
Commented on each change I made to explain why I made them
=> Sorting Fixes

app/networkapi/templates/admin/includes/content_typed_change_list.html, app/networkapi/templates/pages/menus/admin.html
=> Remove ability to create sub-pages

app/networkapi/templates/admin/includes/content_typed_change_list.html
=> Query param needs a value

app/networkapi/filebrowser_s3/storage.py, app/networkapi/filebrowser_s3/templates/filebrowser/include/filelisting.html, app/networkapi/filebrowser_s3/templatetags/s3thumbnails.py, app/networkapi/settings.py
reincluded fbs3 to do easier debugging
=> Reincluded

app/networkapi/settings.py, requirements.txt
update filebrowser_s3 to 0.1.18 with AWS_LOCATION and FILEBROWSER_DIRECTORY hooked up correectly
=> fbs3 0.1.18

app/networkapi/templates/admin/pages/page/change_list.html
I guess this is it? Closes #148
=> Override content_title for page creation

app/networkapi/people/admin.py
Slight hack, @gideonthomas said it's the most reasonable way though. Closes #176
=> Add help text for affiliations model

README.md
=> Add documentation detailing running network-api behind a proxy

app/networkapi/static/css/adminsortable_objects_custom.css, app/networkapi/templates/people/adminsortable_objects_custom.html
=> Indicate featured people in ordering page

app/networkapi/utility/templatetags/settings_value.py
remove a print that slipped in that printed arbitrary settings keys
=> print removal

app/networkapi/static/css/content_typed_change_list.css, app/networkapi/static/js/admin/page_tree.js, app/networkapi/templates/admin/includes/content_typed_change_list.html, app/networkapi/templates/admin/pages/page/change_list.html, app/networkapi/templates/pages/menus/admin.html
closes #208, closes #192, and generally makes things a little nicer and more intuitive.
WIP in terms of "if this is what we like, I can clear this up a little", but ready for review.
=> let's make things look nicer

app/networkapi/static/css/template-overrides.css, app/networkapi/static/js/admin/login-show-hide.js, app/networkapi/templates/admin/login.html
closes https://github.com/mozilla/network-api/issues/191 by implementing the indicated UX
=> google login prominence

appveyor.yml
Adds appveyor.yml for testing that our code can run on Windows
Fixes https://github.com/MozillaFoundation/mofo-devops/issues/518
=> Enable Appveyor testing

app/networkapi/settings.py
Closes https://github.com/mozilla/network-api/issues/230
=> Use Filebrowser_s3 only when `USE_S3` is enabled

app/networkapi/static/js/filebrowser/upload.js, app/networkapi/templates/filebrowser/upload.html
=> Disable upload button during uploads 

app/networkapi/urls.py
related to https://github.com/mozilla/network-api/issues/214
=> Display default 404 page

app/networkapi/templates/highlights/adminsortable_objects_custom.html
https://github.com/mozilla/network-api/issues/244
=> adminsortable_objects_custom.html: Conditionally display object image

app/networkapi/utility/userpermissions.py
fixes https://github.com/mozilla/network-api/issues/254
=> make sure users are assigned to the website so permissions can kick in

app/networkapi/milestones/models.py, app/networkapi/milestones/views.py
Fixes https://github.com/mozilla/network-api/issues/265
=> Retrieve all milestones instead of just upcoming

app/networkapi/static/js/admin/page_tree.js, app/networkapi/templates/pages/menus/admin.html
Fixes https://github.com/mozilla/network/issues/618
=> Enable creation of subpages
